# If you were to add a deployment config for GitHub Actions, you might add a second file called deployment.yml

---
name: GitHub Actions

# Now we are going to set the trigger event for the jobs defined further down on this very same file.
# Next line is same as --> on: [push]
on:
  push:
    branch:
      main

jobs:
  test-lint: # this is the ID of the job
    name: Test and Lint # human-friendly name of the job
    runs-on: ubuntu-24.04 # operating system runner available that we are going to be running our job on. --> Ideal for python projects.
    steps:
      - name: Login to Docker Hub # Human readable name
        uses: docker/login-action@v3 # Allows to use another pre-made action that's provided in the github actions repository, where we can re-use existing actions.
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2 # Checks our code out inside our GHA job. This is needed because the code is not checked out inside the job.

      - name: Tests
        run: docker compose run --rm app sh -c "python manage.py test" # Command that is used for running the unit tests.

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

  